import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/themeProvider';

export const metadata: Metadata = {
  title: 'Tony Terra Nova | Software Engineer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
